# Generated by Django 3.1.4 on 2021-03-07 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms_class', '0003_remove_lmsclass_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_of_lesson', models.CharField(choices=[('LC', 'Lecture'), ('QZ', 'Quiz'), ('AS', 'Assignment'), ('AC', 'Activity'), ('EX', 'Exam')], default='LC', max_length=2)),
                ('term', models.CharField(choices=[('PRE', 'Prelim'), ('MID', 'Midterm'), ('SEM', 'Semi-finals'), ('FIN', 'Finals')], default='PRE', max_length=3)),
                ('deadline', models.DateTimeField()),
                ('lesson_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lms_class.lmsclass')),
            ],
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_description', models.CharField(max_length=1024)),
                ('file', models.FileField(upload_to='')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='lms_lesson.lesson')),
            ],
        ),
    ]
