# Generated by Django 3.1.4 on 2021-03-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_lesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonfile',
            name='file_description',
        ),
    ]
