# Generated by Django 3.1.4 on 2021-03-07 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_lesson', '0002_remove_lessonfile_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfile',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessonfile', to='lms_lesson.lesson'),
        ),
    ]
