# Generated by Django 3.1.4 on 2021-03-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_lesson', '0004_auto_20210314_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type_of_lesson',
            field=models.CharField(choices=[('LC', 'Lecture'), ('QZ', 'Quiz'), ('AS', 'Assignment'), ('AC', 'Activity'), ('EX', 'Exam')], default='QZ', max_length=2),
        ),
    ]
