# Generated by Django 3.1.4 on 2021-03-15 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms_lesson', '0006_auto_20210314_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='total_mark',
            field=models.IntegerField(default=100),
        ),
    ]
