# Generated by Django 3.1.4 on 2021-03-23 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_lesson', '0009_lesson_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='type_of_lecture',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='LectureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturefile', to='lms_lesson.lecture')),
            ],
        ),
    ]
