# Generated by Django 3.1.4 on 2021-03-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_lesson', '0010_auto_20210323_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lesson_class',
            new_name='lecture_class',
        ),
    ]
