# Generated by Django 3.1.4 on 2021-03-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_lesson', '0011_auto_20210323_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='type_of_lecture',
            field=models.CharField(max_length=32),
        ),
    ]
