# Generated by Django 3.1.4 on 2021-03-24 10:50

from django.db import migrations
import lms_lesson.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_lesson', '0013_lecturecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfile',
            name='file',
            field=lms_lesson.models.CustomFileField(upload_to=''),
        ),
    ]
