# Generated by Django 3.1.4 on 2021-03-03 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('class_token', models.CharField(max_length=255)),
                ('course', models.CharField(choices=[('BSCS', 'BSCS'), ('BSED', 'BSED'), ('BAPS', 'BSPS')], max_length=4)),
                ('year', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', 'Grad')], max_length=1)),
                ('semester', models.CharField(choices=[('P', 'PRE'), ('M', 'MID'), ('S', 'SEMI'), ('F', 'FIN')], max_length=1)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_taugth', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
