# Generated by Django 3.1.4 on 2021-03-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_class', '0002_auto_20210303_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmsclass',
            name='semester',
        ),
    ]
