# Generated by Django 3.1.4 on 2021-03-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_class', '0004_auto_20210307_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsclass',
            name='semester',
            field=models.CharField(choices=[('FS', 'First Sem'), ('SS', 'Second Sem')], default='FS', max_length=2),
        ),
    ]
