# Generated by Django 3.1.4 on 2021-03-11 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_class', '0005_auto_20210307_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsclass',
            name='pending_students',
            field=models.ManyToManyField(related_name='pending_class', to=settings.AUTH_USER_MODEL),
        ),
    ]
