# Generated by Django 3.1.4 on 2021-03-16 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_class', '0006_lmsclass_pending_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsclass',
            name='invited_students',
            field=models.ManyToManyField(related_name='invited_class', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LMSClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_bg', models.ImageField(blank=True, default='banner2.png', upload_to='')),
                ('lecture_num', models.IntegerField(default=0)),
                ('quiz_num', models.IntegerField(default=0)),
                ('ass_num', models.IntegerField(default=0)),
                ('act_num', models.IntegerField(default=0)),
                ('exam_num', models.IntegerField(default=0)),
                ('lmsclass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lmsclassinfo', to='lms_class.lmsclass')),
            ],
        ),
    ]
