# Generated by Django 3.1.4 on 2021-03-16 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_class', '0007_auto_20210316_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmsclassinfo',
            name='lecture_num',
        ),
    ]
