# Generated by Django 3.1.4 on 2021-03-16 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_class', '0008_remove_lmsclassinfo_lecture_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.IntegerField(default=0)),
                ('mid', models.IntegerField(default=0)),
                ('sem', models.IntegerField(default=0)),
                ('fin', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='lmsclassinfo',
            name='act_num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='act_num', to='lms_class.termcounts'),
        ),
        migrations.AlterField(
            model_name='lmsclassinfo',
            name='ass_num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ass_num', to='lms_class.termcounts'),
        ),
        migrations.AlterField(
            model_name='lmsclassinfo',
            name='exam_num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_num', to='lms_class.termcounts'),
        ),
        migrations.AlterField(
            model_name='lmsclassinfo',
            name='quiz_num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_num', to='lms_class.termcounts'),
        ),
    ]
