# Generated by Django 3.1.4 on 2021-03-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210302_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('BSCS', 'BSCS'), ('BSED', 'BSED'), ('BAPS', 'BSPS')], default='XXXX', max_length=4),
            preserve_default=False,
        ),
    ]
