# Generated by Django 3.1.4 on 2021-03-07 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_lesson', '0003_auto_20210307_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=-1)),
                ('turned_in', models.BooleanField(default=False)),
                ('graded', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentwork', to='lms_lesson.lesson')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentwork', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentWorkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentworkfile', to='lms_studentwork.studentwork')),
            ],
        ),
        migrations.CreateModel(
            name='StudentWorkComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentworkcomment', to='lms_studentwork.studentwork')),
            ],
        ),
    ]
