# Generated by Django 3.1.4 on 2021-03-10 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_studentwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentworkcomment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentworkcomment', to=settings.AUTH_USER_MODEL),
        ),
    ]
