# Generated by Django 3.1.4 on 2021-03-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_studentwork', '0004_studentwork_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwork',
            name='remark',
            field=models.TextField(default='Good Job :)'),
        ),
    ]
