# Generated by Django 3.1.4 on 2021-03-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_studentwork', '0005_auto_20210311_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='late',
            field=models.BooleanField(default=False),
        ),
    ]
