# Generated by Django 3.1.4 on 2021-03-23 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_lesson', '0010_auto_20210323_1007'),
        ('lms_studentwork', '0006_studentwork_late'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturecomment', to='lms_lesson.lecture')),
            ],
        ),
    ]
