# Generated by Django 3.1.4 on 2021-03-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_studentwork', '0007_lecturecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LectureComment',
        ),
    ]
