# Generated by Django 3.1.4 on 2021-03-25 02:14

from django.db import migrations
import lms_lesson.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_studentwork', '0008_delete_lecturecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentworkfile',
            name='file',
            field=lms_lesson.models.CustomFileField(upload_to=''),
        ),
    ]
