# Generated by Django 3.1.4 on 2021-03-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_admin', '0002_auto_20210329_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='img',
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcementimages', to='lms_admin.announcement')),
            ],
        ),
    ]
