# Generated by Django 3.1.4 on 2021-03-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_admin', '0004_admin_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='model_name',
        ),
    ]
