# Generated by Django 3.1.4 on 2021-03-31 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_admin', '0007_auto_20210329_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='pending_instructors',
            field=models.ManyToManyField(related_name='my_instructor_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
